### ISSUE TITLE
Help for migrating analysis recipes to v0.3

### ISSUE THREAD

**Issue by lmoureaux** [columnflow/columnflow#693]
Hello all!

I noticed that many columnflow [analysis recipes](https://gitlab.cern.ch/cms-analysis/general/analysis_recipes) checks just turned red. After preliminary investigation, this seems related to the recent release of v0.3 with breaking changes.

While I can in general do small fixes myself, the scale of the task here is a bit larger and I'd need your help, especially because the recipes tend to hook into columnflow internals -- this is probably also why they started failing. Hopefully the errors will be quite transparent to you. Here is an example (from [this job](https://gitlab.cern.ch/cms-analysis/general/analysis_recipes/-/jobs/56816005)):
```
Era(name='23post', run=3, year=2023, json_pog_era='2023_Summer23BPix', egamma_year='2023PromptD')
Traceback (most recent call last):
  File "/builds/cms-analysis/general/analysis_recipes/frameworks/columnflow/run.py", line 84, in <module>
    sys.exit(main())
  File "/builds/cms-analysis/general/analysis_recipes/frameworks/columnflow/run.py", line 72, in main
    func(
  File "/builds/cms-analysis/general/analysis_recipes/frameworks/columnflow/cf_analysis/cf_analysis/recipe_scripts/electron_sf.py", line 43, in recipe_electron_sf
    producer.run_setup(
TypeError: recipe electron_sf failed: run_setup() missing 1 required positional argument: 'task'
```

I'll be presenting the work on analysis recipes at a CMS Week plenary so it would be great to fix things before!

**Comment by mafrahm** [comment]
Hi @lmoureaux, we tried to better separate TaskArrayFunctions such as Producers from the tasks themselves. Therefore, we had to change the signature of functions such as the `setup` hook a bit - the `task` argument now needs to be passed separately. I'm also linking the [transition guide](https://columnflow.readthedocs.io/en/latest/user_guide/02_03_transition.html) just for completeness.

It might already be sufficient to add `task=None` to calls of the `producer.run_setup` function, e.g. [here](https://gitlab.cern.ch/cms-analysis/general/analysis_recipes/-/blob/master/frameworks/columnflow/recipe_scripts/electron_sf.py#L43-56)

Let me know if this helped or if we need to look a bit more in depth into this issue.

**Comment by lmoureaux** [comment]
We have more issues actually, the sandbox cannot be created on CERN Gitlab images:
```
Collecting pandas (from coffea==2024.11.0->-r /builds/cms-analysis/general/analysis_recipes/frameworks/columnflow/cf_analysis/modules/columnflow/sandboxes/columnar.txt (line 9))
  Downloading pandas-2.3.0.tar.gz (4.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.5/4.5 MB 153.7 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      + meson setup /tmp/pip-install-vmtgmiks/pandas_34909aff590747aea182a38e822de260 /tmp/pip-install-vmtgmiks/pandas_34909aff590747aea182a38e822de260/.mesonpy-7yd7qsw9 -Dbuildtype=release -Db_ndebug=if-release -Db_vscrt=md --vsenv --native-file=/tmp/pip-install-vmtgmiks/pandas_34909aff590747aea182a38e822de260/.mesonpy-7yd7qsw9/meson-python-native-file.ini
      The Meson build system
      Version: 1.8.1
      Source dir: /tmp/pip-install-vmtgmiks/pandas_34909aff590747aea182a38e822de260
      Build dir: /tmp/pip-install-vmtgmiks/pandas_34909aff590747aea182a38e822de260/.mesonpy-7yd7qsw9
      Build type: native build
      Project name: pandas
      Project version: 2.3.0
      
      ../meson.build:2:0: ERROR: Unknown compiler(s): [['cc'], ['gcc'], ['clang'], ['nvc'], ['pgcc'], ['icc'], ['icx']]
      The following exception(s) were encountered:
      Running `cc --version` gave "[Errno 2] No such file or directory: 'cc'"
      Running `gcc --version` gave "[Errno 2] No such file or directory: 'gcc'"
      Running `clang --version` gave "[Errno 2] No such file or directory: 'clang'"
      Running `nvc --version` gave "[Errno 2] No such file or directory: 'nvc'"
      Running `pgcc --version` gave "[Errno 2] No such file or directory: 'pgcc'"
      Running `icc --version` gave "[Errno 2] No such file or directory: 'icc'"
      Running `icx --version` gave "[Errno 2] No such file or directory: 'icx'"
      
      A full log can be found at /tmp/pip-install-vmtgmiks/pandas_34909aff590747aea182a38e822de260/.mesonpy-7yd7qsw9/meson-logs/meson-log.txt
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
```
I guess I can `dnf install gcc` and see what happens.

**Comment by lmoureaux** [comment]
Installing `gcc` was enough to get the sandbox going.

**Comment by lmoureaux** [comment]
Thanks for the help, it's (mostly) green again! Scroll down to the tables: https://gitlab.cern.ch/cms-analysis/general/analysis_recipes/-/blob/master/README.md?ref_type=heads
