### ISSUE TITLE
Condensing uses and produces columns might break some user implementations

### ISSUE THREAD

**Issue by pkausw** [columnflow/columnflow#591]
Consider this code fragment:

```python
from columnflow.production.cms.pileup import pu_weight

# ... do something
for name in sorted(self[pu_weight].produces):
    weight_map[f"sum_mc_weight_{name}"] = (events.mc_weight * events[name], Ellipsis)
```

This code breaks after commit https://github.com/columnflow/columnflow/commit/5957c068c93c1b5b6816ba6543427f37e726b793 with the following error:

```
awkward.errors.FieldNotFoundError: no field 'pu_weight{,_minbias_xs_up,_minbias_xs_down}' in record with 78 fields

This error occurred while attempting to slice

    <NanoEventsArray [<event 1:                256355:                178678739>, ..., <event 1:                339756:                236809753>] type='...'>

with

    'pu_weight{,_minbias_xs_up,_minbias_xs_down}'
    
```

The solution is known, this issue is for documentation only

**Comment by pkausw** [comment]
The solution to this issue is to switch to the `produced_columns` fields. The snippet is fixed with the following implementation (probs to @mafrahm )

```python

for route in sorted(self[pu_weight].produced_columns):
    name = route.string_column
    weight_map[f"sum_mc_weight_{name}"] = (events.mc_weight * events[name], Ellipsis)

```
